### ISSUE TITLE
Userstories

### ISSUE THREAD

**Issue by d471061c** [d471061c/bibtexting#2]
**Userstories**

Story 1: User can edit and delete references
Confirmators:
    - Edits have an actual impact on the reference
    - Deleted reference is truly removed
    - Edit/Delete won't affect any unintentional references

Story 2: User can attach free form tags to the references
Confirmators:
    - User can add 

Story 3: User can add a new reference (type @inproceedings)
Confirmators:
    - user is presented with a form where the user can input reference's information
    - when the user has finished inputting the data a new "in proceedings"-object is saved to the database

Story 4: User can add a new reference (Type: @article)
Confirmators:
    - New reference is only saved when it contains proper type of data

Story 5: User can search (by title) and view a specific reference in the database 
Confirmators:
    - A reference with a matching title is returned
    - If no reference is found matching the title, no reference is returned
    -A refererence which has a title with unicode characters (Ääkköset) is found and returned to the use

**Comment by basic-ohjelmoia** [comment]
Week 2 user stories:
- bibtex file creation
- new reference types: @book, @inproceedings
- advanced UI
- rename bibtex file

book + inproceedings

tiedoston nimen valitse

jussi - implementoi maven/bibtex pluginin

eero - käyttöliittymän jatko
